version: 2
jobs:
  build:
    docker:
      - image: marcrowo/share-button-study-base:8
        environment:
          DISPLAY: :10
          FIREFOX_BINARY: /firefox/firefox

    working_directory: /share-button-study

    steps:
      - run:
          name: xvfb and openbox
          command: Xvfb $DISPLAY -ac & sleep 1 & openbox
          background: true

      - checkout

      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "/home/ubuntu/.yarn-cache"

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Build .XPI
          command: npm run build

      - run:
          name: Functional tests
          command: npm run test

      - store_artifacts:
          path: "extension/share-button-study.xpi"
